export const MUSIC_TRACKS = [
  { name: "Lemon Light", file: "/music/Lemon_Light.mp3" },
  { name: "Morning Glow", file: "/music/Morning_Glow.mp3" },
  { name: "Quivering Aria", file: "/music/Quivering_Aria.mp3" },
  { name: "Radiant Journey", file: "/music/Radiant_Journey.mp3" },
  { name: "Snow Dance Party", file: "/music/Snow_Dance_Party.mp3" },
  { name: "Snowfall at Ease", file: "/music/Snowfall_at_Ease.mp3" },
  { name: "Soft Winter Motion", file: "/music/Soft_Winter_Motion.mp3" },
  { name: "The Toy Soldier's Secret Dance", file: "/music/The_Toy_Soldiers_Secret_Dance.mp3" },
  { name: "The Toy Soldier's Secret Dance 2", file: "/music/The_Toy_Soldiers_Secret_Dance_2.mp3" },
  { name: "Under the Fairy Lights", file: "/music/Under_the_Fairy_Lights.mp3" },
  { name: "Vibrant Day", file: "/music/Vibrant_Day.mp3" },
  { name: "Vibrant Day 2", file: "/music/Vibrant_Day_2.mp3" },
  { name: "Vibrant Day 3", file: "/music/Vibrant_Day_3.mp3" },
  { name: "Warmth in the Middle", file: "/music/Warmth_in_the_Middle.mp3" },
];
